name: Deploy to XDN
on: [push]
jobs:
  dump-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        env:
          GH_SECRETS: ${{ toJson(secrets) }}
        run: echo "$GH_SECRETS"
